apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zpwf2r1fx-nodejs 
  janus-idp.io/tekton: zpwf2r1fx-nodejs
  backstage.io/kubernetes-id: zpwf2r1fx-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zpwf2r1fx-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml