apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zpwf2r1fx-nodejs
  janus-idp.io/tekton: zpwf2r1fx-nodejs
  backstage.io/kubernetes-id: zpwf2r1fx-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zpwf2r1fx-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
