apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zpwf2r1fx-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zpwf2r1fx-nodejs 
  name: zpwf2r1fx-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: zpwf2r1fx-nodejs 
